netsquid_random_state_seed: random

matrix:
  requests_until: null
  parameters:
    num_pairs:
      type: int
      distribution: normal
      mean: 50
      stdev: 0
  start_time:
    distribution: exponential
    interval: null
