network: network

heralding_station:
  properties:
    num_bsm_units: 1
    bsm_properties:
      p_dark: 5.0e-7
      det_eff: 0.8
      visibility: 0.9

host:
  properties:
    nqubits: 1

repeater:
  properties:
    nqubits: 2

router:
  properties:
    nqubits: null

classical_connection:
  properties: &classical_fibre_properties
    connection_properties:
      length: 25
    delay_properties:
      c: 206753.41931034482

quantum_connection:
  properties:
    << : *classical_fibre_properties
    loss_properties:
      p_loss_init: 0.0
      p_loss_length: 0.5
